version: '3.8'

services:
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/vritat
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_HOST=db
      - DB_NAME=${POSTGRES_NAME}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5434:5432"

