version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: compose/prod/Dockerfile_backend
    image: esskimosa/vritat-backend:latest
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/vritat
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: compose/prod/Dockerfile_frontend
    image: esskimosa/vritat-frontend:latest
    env_file:
      - ./frontend/.envs/.prod/.react
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/node_modules:/app/node_modules

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5434:5432"

  nginx:
    build:
      context: .
      dockerfile: compose/prod/Dockerfile_ngnix
    image: esskimosa/vritat-nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./compose/prod/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
