# Generated by Django 4.2.6 on 2024-06-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_news_deleted_news_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
