# Generated by Django 4.2.6 on 2024-06-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_news_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
