# Generated by Django 5.0.3 on 2024-03-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('title', models.TextField()),
                ('link', models.URLField()),
                ('published', models.DateField()),
                ('summary', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
