# Generated by Django 5.0.3 on 2024-05-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sentiment',
            field=models.FloatField(default=0),
        ),
    ]
