# Generated by Django 4.2.6 on 2024-03-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_newssport_alter_news_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsSport',
        ),
    ]
