# Generated by Django 5.0.3 on 2024-03-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_news_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_active',
        ),
    ]
