# Generated by Django 5.0.3 on 2024-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_remove_news_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sentiment',
            field=models.FloatField(default=0),
        ),
    ]
