# Generated by Django 5.0.3 on 2024-03-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_news_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='sentiment',
        ),
    ]
