# Generated by Django 4.2.6 on 2024-04-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0008_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
