# Generated by Django 4.2.6 on 2024-04-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0009_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
