FROM node:18-alpine

WORKDIR /app

COPY ../frontend/package.json ../frontend/yarn.lock ./

RUN yarn config set network-timeout 600000
RUN yarn install --production --verbose

COPY ../frontend .

# ENV NODE_ENV=production

# RUN cp .env.production .env

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]