FROM python:latest

ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y postgresql-client

WORKDIR /vritat

COPY requirements.txt .
RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

COPY . .

RUN python manage.py collectstatic --noinput

EXPOSE 8000

# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]
CMD ["python3", "manage.py", "runserver"]