FROM node:18-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn config set network-timeout 600000
RUN yarn install --production --verbose

COPY ../frontend .

ENV NODE_ENV=development

# RUN cp .env.dev .env

EXPOSE 3000

CMD ["yarn", "start"]