name: Deploy to EC2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
          
      - name: Write EC2 Fingerprint to the runner known hosts
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan -p 22 ${{ secrets.EC2_HOST }} >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.EC2_HOST }} ecdsa-sha2-nistp256 ${EC2_HOST_FINGERPRINT}" > /home/runner/.ssh/known_hosts

          
      - name: Debug previous action
        run: |
          cat /home/runner/.ssh/known_hosts

      - name: Write EC2 Private key to the runner
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > /home/runner/.ssh/id_ed25519
          chmod 600 /home/runner/.ssh/id_ed25519
        

      - name: Write and transfer .env file to EC2 instance
        env:
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}
        run: |
          echo "$PRODUCTION_ENV" > /home/runner/.env
          scp -o StrictHostKeyChecking=no -i .ssh/id_ed25519 /home/runner/.env ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ec2-user/search_engine_vritat/.env
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "ls /home/ec2-user/"
          # cat /home/runner/.env | ssh -v -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_ed25519 ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cat > /home/ec2-user/search_engine_vritat/.env"

     # - name: Stop app, pull new image, start backend container in EC2
      #  run: |
       #   ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ec2-user/search_engine_vritat"
        #    docker-compose down
         #   docker-compose pull
          #  docker-compose up -d backend

      - name: Stop app, pull new image, start backend and frontend in EC2
        run: |
          ssh -t -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_ed25519 ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/search_engine_vritat
            docker-compose down
            docker-compose pull
            docker-compose up -d backend
            cd frontend
            yarn install --production
            yarn start
          EOF
