name: Deploy to EC2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub (or your container registry)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up .env file
        run: echo "${{ secrets.PRODUCTION_ENV }}" > .env

      - name: Build and Push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Add EC2 host to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_HOST_FINGERPRINT }}" >> ~/.ssh/known_hosts

      - name: SSH into EC2 instance and copy .env file
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ec2-user/search_engine_vritat
            echo "${{ secrets.PRODUCTION_ENV }}" > /home/ec2-user/search_engine_vritat/.env

      - name: SSH into EC2 instance to restart Docker services
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/search_engine_vritat
            docker-compose down
            docker-compose pull
            docker-compose up -d
