name: Deploy to AWS EC2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up environment variables for Docker
        env:
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}
        run: echo "$PRODUCTION_ENV" > .env

      - name: Build and push backend image
        run: |
          DOCKER_BUILDKIT=1 docker-compose -f docker-compose.prod.yml --env-file .env build
          docker push esskimosa/vritat-backend:latest
          docker push esskimosa/vritat-frontend:latest

      - name: Cleanup temporary .env file
        run: rm .env

      - name: Write EC2 Fingerprint to the runner known hosts
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan -p 22 ${{ secrets.EC2_HOST }} >> /home/runner/.ssh/known_hosts

      - name: Write EC2 Private key to the runner
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > /home/runner/.ssh/id_ed25519
          chmod 600 /home/runner/.ssh/id_ed25519

      - name: Write and transfer .env file to EC2 instance
        env:
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}
        run: |
          echo "$PRODUCTION_ENV" > .env
          scp -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_ed25519 .env ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ec2-user/search_engine_vritat/.env
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "ls /home/ec2-user/"

      - name: SSH into EC2, stop/pull/start container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            cd /home/ec2-user/search_engine_vritat
            docker-compose down
            docker-compose pull
            docker-compose up -d
            docker ps

