name: Deploy to AWS EC2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Write and transfer .env file to EC2 instance
        env:
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}
        run: |
          echo "$PRODUCTION_ENV" > /home/runner/.env
          # echo "$PRODUCTION_ENV" > /home/runner/work/search_engine_vritat/search_engine_vritat/.env
          scp -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_ed25519 /home/runner/.env ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ec2-user/search_engine_vritat/.env
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "ls /home/ec2-user/"


      - name: Build and push backend image
        run: |
          DOCKER_BUILDKIT=1 docker-compose -f docker-compose.prod.yml build
          docker push esskimosa/vritat-backend:latest
          docker push esskimosa/vritat-frontend:latest
          
      - name: Write EC2 Fingerprint to the runner known hosts
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan -p 22 ${{ secrets.EC2_HOST }} >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.EC2_HOST }} ecdsa-sha2-nistp256 ${EC2_HOST_FINGERPRINT}" >> /home/runner/.ssh/known_hosts
          
      - name: Write EC2 Private key to the runner
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > /home/runner/.ssh/id_ed25519
          chmod 600 /home/runner/.ssh/id_ed25519
          
          
      - name: SSH into EC2, stop/pull/start container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/search_engine_vritat
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            docker ps -aq | xargs docker stop | xargs docker rm
            docker pull esskimosa/vritat-backend:latest
            docker pull esskimosa/vritat-frontend:latest

      - name: Start App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/search_engine_vritat
            docker-compose -f docker-compose.prod.yml up -d
            docker-compose -f docker-compose.prod.yml run --rm backend python manage.py migrate
            docker-compose -f docker-compose.prod.yml run --rm backend python manage.py loaddata superuser.json
            docker-compose -f docker-compose.prod.yml run --rm backend python manage.py loaddata base_users.json
            docker ps
