name: Deploy to EC2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub (or your container registry)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker images
        run: |
          docker-compose -f /github/workspace/docker-compose.yml build
          docker-compose -f /github/workspace/docker-compose.yml push

      - name: Add EC2 host to known hosts
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.EC2_HOST }} ecdsa-sha2-nistp256 ${EC2_HOST_FINGERPRINT}" >> /home/runner/.ssh/known_hosts

      - name: Debug SSH Connection
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > /tmp/key.pem
          chmod 400 /tmp/key.pem
          ssh -i /tmp/key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "echo Connected"

      - name: Copy .env file to EC2 instance
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}
        run: |
          echo "$EC2_PRIVATE_KEY" > /tmp/key.pem
          chmod 400 /tmp/key.pem
          echo "$PRODUCTION_ENV" > /tmp/.env
          scp -o StrictHostKeyChecking=no -i /tmp/key.pem /tmp/.env ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ec2-user/search_engine_vritat/.env

      - name: SSH into EC2 instance
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command: |
            cd /home/ec2-user/search_engine_vritat
            docker-compose down
            docker-compose pull
            docker-compose up -d
